python3 main.py \
--size 256 \
--num_classes 1 \
--in_chans 3 \
--batch_size 32 \
--lr 0.0001 \
--epochs 200 \
--patience 20 \
--arch vit_base \
--root_dir <training-data-directory> \
--run run \
--gpu_ids 0